### PR TITLE
Update packet IDs, make MapCacher more useful for other plugins

### PR DESCRIPTION
**Pull request by apemanzilla**
Relatively minor change but this allows other plugins to more easily access MapCacher's data (as seen in the changes to the AutoNexus plugin)

### CODE REVIEW

**Comment by apemanzilla** [comment]
I've updated the packet IDs for 27.7.X2 as well.

**Comment by apemanzilla** [comment]
@TheKronks the game data XML still needs to be updated, forgot to add that to this PR

**Comment by TheKronks** [comment]
The packet id commit got merged along with it

**Comment by apemanzilla** [comment]
Ah, good.

**Comment by apemanzilla** [comment]
I know, I mean the complete enemy/item/object data, which I didn't update. Stuff like the Ring of Decades won't be in the current version.

**Pull request merged**
