### PR TITLE
More complete game data system

### PR DESCRIPTION
**Pull request by apemanzilla**
I've implemented the stuff discussed in #17. The game XML is now parsed and mapped to different `struct`s that offer far more data than `Serializer`, and the raw XML can also be accessed publicly. I've also marked `Serializer` as obsolete and updated the plugins to use `GameData` instead. Old plugins should remain compatible, but they may need to be recompiled.

The `GameData` system is a little bit more complex for simple lookups, but offers a lot more data to plugins, and if necessary helper methods can be written to simplify basic operations.

I'd recommend that you test everything out and skim over my code just to make sure I didn't break anything by mistake :stuck_out_tongue:

### CODE REVIEW

**Comment by apemanzilla** [comment]
Actually I'm going to work on this a little bit more. Closing for now.

**Comment by TheKronks** [comment]
It's looking really good!
This is what we needed all along, let me know when you want to take a look again for the merge.

**Comment by apemanzilla** [comment]
I think I'm almost done. I have a couple minor fixes to push and then I'll open another PR, should be ready within the hour.

**Comment by apemanzilla** [comment]
Alright, should be all set now. I've tested it briefly but there's bound to be some bugs which I'll patch, just let me know if you find any.

**Comment by TheKronks** [comment]
Thank you very much for the contribution

**Comment by apemanzilla** [comment]
No problem! Now that I have this written I can work on a plugin I've wanted to write too :stuck_out_tongue:

**Comment by TheKronks** [comment]
I have some smaller changes regarding the XML stuff taht I'll commit ASAP, on vacation atm so it's hard :P

**Comment by PixelZerg** [comment]
The GameData class has fields for all of the XML files apart from `complete gamedata.xml`
The `complete gamedata.xml` needs to be implemented too.

**Pull request merged**
